export const environment = {
  AZURE_OPENAI_ENDPOINT: '',
  AZURE_OPENAI_KEY: '',
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT: '',
  AZURE_SEARCH_ENDPOINT: '',
  AZURE_SEARCH_INDEX: '',
  AZURE_SEARCH_KEY: ''
};
